#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 检查子模块是否有新的提交
git submodule foreach -q 'git fetch --quiet && git status --porcelain | grep -q "Your branch is ahead"'

if [ $? -eq 0 ]; then
  echo "检测到子模块有新的提交，正在更新..."

  # 更新子模块
  git submodule update --remote --merge

  # 添加子模块的更改到暂存区
  git add .

  # 提交更改
  git commit -m "自动更新子模块"

  # 推送更改到远程仓库
  git push
else
  echo "子模块没有新的提交。"
fi