#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 更新子模块路径
SUBMODULE_PATH="/readMe"

# 检查子模块是否有新的提交
if cd "$SUBMODULE_PATH" && git fetch --quiet && git status --porcelain | grep -q "Your branch is ahead"; then
  echo "检测到子模块有新的提交，正在更新..."
  # 返回到主仓库目录
  cd -
  # 更新子模块
  git submodule update --remote "$SUBMODULE_PATH"

  # 添加子模块的更改到暂存区
  git add "$SUBMODULE_PATH"

  # 提交更改
  git commit -m "自动更新子模块"

  # 推送更改到远程仓库
  git push
else
  echo "子模块没有新的提交。"
fi